@startuml
autonumber
actor "Collaborator" as COL

activate COL
COL -> ":System" : beggins the creation of a payment transaction.
activate ":System"
":System" --> COL :  asks for the required data(brief description of the task, \ndetails about the execution of the task and \ninformation about the freelancer that worked in the task)
deactivate ":System"

COL -> ":System" : introduces the required data
activate ":System"
":System" --> COL : shows the data to the Collaborator and asks him to confirm.
deactivate ":System"

COL -> ":System" : confirms
activate ":System"
":System" --> COL : registers the data and informs the Collaborator that\n the operation was successful.
deactivate ":System"

deactivate COL
@enduml
