@startuml
autonumber
actor "Collaborator" as COL
activate COL
COL -> ":System" : initiates the creation of the task
activate ":System"
":System" --> COL : asks for the data \n(id, brief description, time duration(in hours), cost per hour(in euros), task category)
deactivate ":System"

COL -> ":System" : writes the data
activate ":System"
":System" --> COL : shows the data and asks for confirmation
deactivate ":System"

COL -> ":System" : confirms the data
activate ":System"
":System" --> COL : informs about the success of the operation
deactivate ":System"

deactivate COL

@enduml
