

@startuml
class CreateTransactionUI{
  }

class CreateTransactionController{
  +getTaskList()
  +getFreelancerList()
  +createNewTransaction(task, freel, endDate, delay, qow)
  +registerTransaction()
  }

class Organization{
  -String nome
  -String email
  -String nif
  +getTaskList()
  +getRTrans()
  }

class TaskList{
  +getTaskList()
  }

class Platform{
  +getRFree()

  }

class RegisterFreelancer{
  +getListFreelancers()
  }

class RegisterTransaction{
  +createNewTransaction(task, freel, endDate, delay, qow)
  +registerTransaction(trans)
  +validateTransaction(trans)
  +addTransaction(trans)
  }

class TransactionExecution{
  -Data endDate
  -double delay
  -String descriptionOfQuality
  +create(task, freel,endDate, delay, qow, payment)
  }

class Freelancer{
  -String idF
  -String name
  -String levelExpertise
  -String email
  -String nif
  -String ibanAccount
  -String country
  }

class Collaborator{
  -String nome
  -String email
  }

class Task{
  -String idT
  -String description
  -Time timeDuration
  -double costHour
  -String taskCategory
  }

class Payment{
  -valueE
  -valueC
  +create(costEuros, costCurrency)
  }
  


CreateTransactionController ..> Organization
CreateTransactionController ..> TaskList
CreateTransactionController ..> Platform
CreateTransactionController ..> RegisterFreelancer
CreateTransactionController ..> RegisterTransaction
CreateTransactionController ..> TransactionExecution

CreateTransactionUI ..> CreateTransactionController

Freelancer "1" -- "1" Payment: receives >

Platform "1" -- "1..*" RegisterTransaction: has >
RegisterTransaction "1" -- "*" TransactionExecution: has >
Platform "1" -- "1..*" Organization: has registered >
Platform "1" -- "1..*" RegisterFreelancer: has >
RegisterFreelancer "1" -- "*" Freelancer: has >

Organization "1" -- "1" Collaborator: has >
Organization "1" -- "1" TaskList: has >

TaskList "1" -- "*" Task: has >

Collaborator "1" -- "1..*" TransactionExecution: creates >
Collaborator "1" -- "1" User: acts as >

Task "1..*" -- "1" Freelancer: made by >


TransactionExecution "1" --"1" Payment: originates
TransactionExecution "1" -- "1" Freelancer: related to the work of
TransactionExecution "1" --"1" Task: has
TransactionExecution "1" --"1" Freelancer: has



@enduml