@startuml
autonumber

participant ":Plataform" as PLAT
participant "task\n:DoPaymentTask" as TASK
participant "t\n:timer" as TI
participant "RegistOrganizations" as RORGS
participant "lo\n:List<Organazation>" as LO
participant "org\n:Organization" as O
participant "def\n:DefinePayment" as DP



[o-> PLAT : schedulesPayment(email)
activate PLAT

PLAT --> TASK** : create( )



PLAT -> RORGS : lo = getLO()
activate RORGS
deactivate RORGS

PLAT -> LO : org = get(i)
activate LO
deactivate LO
PLAT -> O : dp = getDefinePayment()
activate O
deactivate O
PLAT -> DP : date = getDate()
activate DP
deactivate DP
PLAT -> DP : time = getTime()
activate DP
deactivate DP
PLAT -> DP : nrDays = getNrDays()
activate DP
deactivate DP

PLAT -> PLAT : period = calculatePeriod(nrDays)


PLAT -> PLAT : interval = calculatedifference(date, time)


PLAT --> TI** : create( )
PLAT -> TI : scheduleAtFixedRate(task, interval, period)
activate TI
deactivate TI
deactivate PLAT

TI -> TASK : run( )
activate TI
activate TASK
TASK -> TASK : DoPayment()
ref over TASK : UC7_SD_DoPayment
activate TASK
deactivate TASK
deactivate TASK
deactivate TI




@enduml