@startuml

skinparam classAttributeIconSize 0
left to right direction


class DoPaymentTask{
    +DoPayment(org)
    +calculateCost(costHour, TimeDuration)
    +convertToCurrency(costHour, TimeDuration)
}

class Platform{
    +getRegisterFreelancer()
    +getRT()
}

class Organization{

    +getTaskList()
}

class RegisterFreelancer{
    +getFreelancer()
}



class Freelancer{
    +getCountry()
}

class TaskList{
    +getTask(i)
}

class Task{
    +getIsPayed()
    +getCostHour()
    +getTimeDuration()
}

class RegisterTransaction{
    +gettltr()
}

class Transaction {
    +getFreelancer()
    +getTask()
}

class Payment{
    +Payment(sum, curr, nltr)
    +generateReceipt(country)
}

class Writer{
    +writeOrg(org, sum, curr)
}

DoPaymentTask ..> Platform
DoPaymentTask ..> Organization
Platform "1" -- "1" RegisterFreelancer : has
RegisterFreelancer "1" -- "1..*" Freelancer : has
Organization "1" -- "1" TaskList : has
TaskList "1" -- "1..*" Task : has
Platform "1" -- "1..*" Organization : has
Platform "1" -- "1..*" RegisterTransaction : has
RegisterTransaction "1" -- "1..*" Transaction : has
DoPaymentTask ..> RegisterFreelancer
DoPaymentTask ..> Task
DoPaymentTask ..> RegisterTransaction
DoPaymentTask ..> Transaction
DoPaymentTask ..> Freelancer
DoPaymentTask "1" -- "1..*" Payment : creates
DoPaymentTask ..> Payment
Payment "1" --> "1" Freelancer
DoPaymentTask ..> Writer

@enduml