@startuml
autonumber
actor "Timer" as TIM

activate TIM
TIM -> ":System" : The timer starts the automatic payment process\nusing the payment list, triggering the process \nat the defined date and time.

activate ":System"
deactivate ":System"
deactivate TIM

@enduml