@startuml
autonumber

participant "Payment" as PA


participant "Receipt" as R
participant "Writer" as W

[o-> PA : generateReceipt(country)
activate PA


PA --> R** : create(nltr, sum, curr)

PA -> R : genEmail()
activate R
R -> W : genEmail()
activate W
deactivate W
deactivate R



deactivate PA
@enduml