@startuml
autonumber

actor "Administrator" as ADM
participant ":Regist\nOrganizacionUI" as UI
participant ":RegistOrganization\nController" as CTRL
participant ":Plataform" as PLAT
participant "ro:Regist\nOrganizations" as ORGS
participant "Organization" as _ORG
participant "org:Organization" as ORG
participant "add:Address" as ADD
participant "colab:Collaborator" as COLAB
participant "manager:Manager" as MNGR


ADM -> UI : inserts the information
activate UI

UI -> CTRL : newOrganization(name,email,NIF,street,doorNumber,locality, nameC, emailC, phoneNumberC, nameM, emailM, phoneNumberM)
activate CTRL

CTRL -> PLAT: ro = getRegistOrganizations()
activate PLAT
deactivate PLAT

CTRL -> ORGS: org = newOrganization(name,email,NIF,street,doorNumber,locality, nameC, emailC, phoneNumberC, nameM, emailM, phoneNumberM)
activate ORGS

ORGS -> _ORG: end=newAddress(street, doorNumber, locality)
activate _ORG
_ORG --> ADD ** : create(street, doorNumber, locality)
deactivate _ORG

ORGS -> _ORG: manager=newManager(name, email, role, phoneNumber)
activate _ORG
_ORG --> MNGR ** : create(name, email, role, phoneNumber)
deactivate _ORG

ORGS -> _ORG: collab=newCollaborator(name, email, role, phoneNumber)
activate _ORG
_ORG --> COLAB ** : create(name, email, role, phoneNumber)
deactivate _ORG

ORGS --> ORG ** : create(name, email, nif, address, collaborator, manager)
deactivate ORGS

CTRL -> ORGS : validateOrganization(org)
activate ORGS
deactivate ORGS

deactivate CTRL
UI --> ADM : shows information and a requests confirmation
deactivate UI

ADM -> UI : confirms
activate UI

UI -> CTRL: registOrganization()
activate CTRL
CTRL -> ORGS: registOrganization(org)
activate ORGS

ORGS -> ORGS: validatesOrganization(org)

ref over ORGS, COLAB, MNGR, PLAT
  UC1_SD_RegistUser
end ref

ORGS -> ORGS: addOrganization(org)
deactivate ORGS

deactivate CTRL
UI --> ADM : successful operation
deactivate UI

deactivate ADM
@enduml
