@startuml
skinparam classAttributeIconSize 0
left to right direction

class WatchStatisticsUI {
}

class WatchStatisticsController {
  +getOverallStatistics()
}
class Platform {
    +getRegisterFreelancer()
    +getOrgaanizacaoByEmail(email)
    +getListTransactions()
}

class RegisterFreelancer{
  +getListFreelancer()
  +getFreelancers()
}

class Payment {
  -double valueE
  -double valueC
  +getListTransactions()
}

class Freelancer{
  -String freeID
  -String name
  -String levelExp
  -String email
  -String nif
  -String iban
  -String country
  +getListPayments()
  +averageOfEachFreelancer(PaymentTotal)
  +calculateDeviation(averageFreel,payment)
  +calculateDeviation(sumAllPaymentsDeviation)
  +deviationDelay(delayTask,averageDelayOfFreelancer)
  +calculateDeviationOfAllFreelancers(sumDelayOfAllFreelancers)
}

class TaskExecution {
  -Data endDate
  -double delay
  -String descriptionOfQuality
  +getDelayByTask(task)
}

class Transaction {
  +getPaymentValue() 
  +getTask()
  +getFreelancer()
}

class Organization{
  -String nome
  -String email
  -String nif
  +getTaskList()
  }



WatchStatisticsUI ..> WatchStatisticsController
WatchStatisticsController ..> Platform
WatchStatisticsController ..> Payment
WatchStatisticsController ..> Transaction
WatchStatisticsController ..> Freelancer
WatchStatisticsController ..> TaskExecution
WatchStatisticsController ..> Organization

Platform "1" --> "1" RegisterFreelancer: has
Platform "1" --> "*" Organization: has
Platform "1" --> "*" Transaction: has
RegisterFreelancer "1" --> "*" Freelancer: has
Freelancer "1" --> "1.." Payment: has
Payment "1" --> "1..*" Transaction: has
Transaction "1" --> "1" TaskExecution: creates




@enduml