@startuml
autonumber
'hide footbox
actor "Manager" as ADM

participant ":PaymentUI" as UI
participant ":DefinePaymentController" as CTRL
participant "Platform" as P
participant "rorgs\n:RegisterOrganization" as RO
participant "org\n:Organization" as O
participant "dpay:DefinePayment" as DPAY



activate ADM
ADM -> UI : The manager of the organization selects the processment cycle of payment transactions.
activate UI

UI -> CTRL : getOrg()
activate CTRL


CTRL -> P : rorgs = getRorgs()
activate P
deactivate P


CTRL -> RO : org = getOrganizationByUserEmail(email)
activate RO
deactivate RO



deactivate CTRL

UI --> ADM : The System asks for the day of the month, the time of the day and the recurrence time period (e.g. 7 days).
deactivate UI

ADM -> UI : The Manager inserts the information.
activate UI

UI -> CTRL : newDefinePayment(time, date, nrDays)
activate CTRL


CTRL -> O : define = newDefinePayment(time, date, nrDays)
activate O
O -> DPAY** : create(time, date, nrDays)
deactivate O

CTRL -> O : validatesDefinePayment(define)
activate O
deactivate O

deactivate CTRL

UI --> ADM : shows the information and asks for confirmation.
deactivate UI

ADM -> UI : confirms the data
activate UI

UI -> CTRL : registerDefinePayment()
activate CTRL

CTRL -> DPAY : registersDefinePayment(define)
activate DPAY
DPAY -> DPAY : validatesDefinePayment(define)
deactivate DPAY
CTRL -> O : setDefinePayment(define)
activate O
deactivate O

CTRL -> P : schedulesPayment(email)
activate P
deactivate P

deactivate CTRL

UI -> ADM : informs about the success of the operation
deactivate UI
deactivate ADM




@enduml
