@startuml
autonumber
actor "Tempo" as TIM

activate TIM
TIM -> ":Sistema" : O Tempo inicia o processo de seriação automática à hora estipulada.
activate ":Sistema"
deactivate ":Sistema"
deactivate TIM

@enduml