@startuml

class WatchStatisticsController{
  }

class Statistics {
  +getPaymentDeviationOfEachFreelancer(String email, List<TransactionExecutino> ltr)
  +getTaskExecutionDelayOfEachFreelancer(String email, List<TransactionExecutino> ltr)
  +getTaskExecutionDelayOfAllFreelancers(List<TransactionExecutino> ltr)
  +getPaymentDeviationOfAllFreelancers(List<TransactionExecutino> ltr)
  }


WatchStatisticsController ..> Statistics


@enduml